import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { StructuredCaller } from '../agents/structured-caller.js';
import type { RunAgentOptions } from '../agents/runner.js';
import type { AgentResponse, WorkflowConfig } from '../core/models/index.js';
import { WorkflowEngine } from '../core/workflow/index.js';
import type { StreamEvent } from '../shared/types/provider.js';
import { normalizeRule } from '../infra/config/loaders/workflowRuleNormalizer.js';

vi.mock('../agents/runner.js', () => ({
  runAgent: vi.fn(),
}));

import { runAgent } from '../agents/runner.js';

function response(overrides: Partial<AgentResponse>): AgentResponse {
  return {
    persona: 'coder',
    status: 'done',
    content: 'done',
    timestamp: new Date('2026-06-28T00:00:00Z'),
    ...overrides,
  };
}

function workflowConfig(): WorkflowConfig {
  return {
    name: 'report-fallback-it',
    maxSteps: 3,
    initialStep: 'implement',
    steps: [{
      name: 'implement',
      persona: 'coder',
      personaDisplayName: 'Coder',
      instruction: 'Implement the task',
      passPreviousResponse: false,
      outputContracts: [{ name: 'review.md' }],
      rules: [
        normalizeRule({ condition: 'approved', next: 'COMPLETE' }),
        normalizeRule({ condition: 'needs_fix', next: 'ABORT' }),
      ],
    }],
  };
}

function queueAttempt(result: AgentResponse, streamEvents: StreamEvent[] = []): void {
  vi.mocked(runAgent).mockImplementationOnce(async (persona, task, options) => {
    options?.onPromptResolved?.({
      systemPrompt: typeof persona === 'string' ? persona : '',
      userInstruction: task,
    });

    for (const event of streamEvents) {
      options?.onStream?.(event);
    }

    return result;
  });
}

describe('WorkflowEngine report fallback integration', () => {
  let tmpRoot: string;

  beforeEach(() => {
    tmpRoot = mkdtempSync(join(tmpdir(), 'takt-report-fallback-it-'));
    vi.mocked(runAgent).mockReset();
  });

  afterEach(() => {
    if (existsSync(tmpRoot)) {
      rmSync(tmpRoot, { recursive: true, force: true });
    }
  });

  it('should pass configured fallback provider to the final report runAgent call and write the report', async () => {
    queueAttempt(response({
      content: '[IMPLEMENT:1]\nPhase 1 output',
      sessionId: 'opencode-session-1',
    }));
    queueAttempt(response({ content: '# Report\nfirst attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-1', tool: 'read', input: {} },
    }]);
    queueAttempt(response({ content: '# Report\nretry attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-2', tool: 'bash', input: {} },
    }]);
    queueAttempt(response({
      content: '# Report\nGenerated by fallback provider',
      sessionId: 'codex-fallback-session',
    }));
    const structuredCaller: StructuredCaller = {
      judgeStatus: vi.fn().mockImplementation(async (_structured, _tag, _candidates, options) => {
        options.onStructuredPromptResolved?.({
          systemPrompt: 'conductor-system',
          userInstruction: 'structured prompt',
        });
        return { candidateIndex: 0, method: 'structured_output' };
      }),
      evaluateCondition: vi.fn(),
      decomposeTask: vi.fn(),
      requestMoreParts: vi.fn(),
    };

    const attemptTelemetry: Array<{
      readonly provider: string;
      readonly providerModel: string;
    }> = [];
    const reportProvenance: Array<{
      readonly provider: string;
      readonly model: string;
    }> = [];
    const engine = new WorkflowEngine(workflowConfig(), tmpRoot, 'Task: implement fallback', {
      projectCwd: tmpRoot,
      provider: 'opencode',
      model: 'opencode/qwen3-coder-next',
      reportFallbackProvider: {
        provider: 'codex',
        model: 'gpt-5-report',
      },
      reportDirName: 'report-fallback-it',
      structuredCaller,
      onDelegatedAgentUsage: (context) => {
        attemptTelemetry.push({
          provider: context.provider,
          providerModel: context.providerModel,
        });
      },
    });
    engine.on('step:report', (_step, _path, _name, context) => {
      reportProvenance.push({
        provider: context.provider,
        model: context.model,
      });
    });

    const state = await engine.run();

    expect(state.status).toBe('completed');
    expect(readFileSync(join(tmpRoot, '.takt', 'runs', 'report-fallback-it', 'reports', 'review.md'), 'utf-8'))
      .toContain('Generated by fallback provider');
    expect(runAgent).toHaveBeenCalledTimes(4);
    expect(structuredCaller.judgeStatus).toHaveBeenCalledTimes(1);
    expect(structuredCaller.judgeStatus).toHaveBeenCalledWith(
      expect.any(String),
      expect.any(String),
      [{ label: 'approved' }, { label: 'needs_fix' }],
      expect.objectContaining({
        stepName: 'implement',
        resolvedProvider: 'opencode',
        resolvedModel: 'opencode/qwen3-coder-next',
      }),
    );

    const fallbackOptions = vi.mocked(runAgent).mock.calls[3]?.[2] as RunAgentOptions;
    expect(fallbackOptions).toEqual(expect.objectContaining({
      resolvedProvider: 'codex',
      resolvedModel: 'gpt-5-report',
      permissionMode: 'readonly',
      allowedTools: [],
      sessionId: undefined,
    }));
    expect(reportProvenance).toEqual([{
      provider: 'opencode',
      model: 'opencode/qwen3-coder-next',
    }]);
    expect(attemptTelemetry).toEqual(expect.arrayContaining([{
      provider: 'codex',
      providerModel: 'gpt-5-report',
    }]));
  });

  it('should pass DeepSeek provider options to the report fallback call', async () => {
    const providerOptions = {
      deepseekHarness: { maxTokens: 4096, reasoningEffort: 'max' as const },
    };
    queueAttempt(response({
      content: '[IMPLEMENT:1]\nPhase 1 output',
      sessionId: 'opencode-session-1',
    }));
    queueAttempt(response({ content: '# Report\nfirst attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-1', tool: 'read', input: {} },
    }]);
    queueAttempt(response({ content: '# Report\nretry attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-2', tool: 'bash', input: {} },
    }]);
    queueAttempt(response({
      content: '# Report\nGenerated by DeepSeek fallback',
      sessionId: 'deepseek-fallback-session',
    }));
    const structuredCaller: StructuredCaller = {
      judgeStatus: vi.fn().mockImplementation(async (_structured, _tag, _candidates, options) => {
        options.onStructuredPromptResolved?.({
          systemPrompt: 'conductor-system',
          userInstruction: 'structured prompt',
        });
        return { candidateIndex: 0, method: 'structured_output' };
      }),
      evaluateCondition: vi.fn(),
      decomposeTask: vi.fn(),
      requestMoreParts: vi.fn(),
    };
    const attemptTelemetry: Array<{
      readonly provider: string;
      readonly providerModel: string;
    }> = [];
    const engine = new WorkflowEngine(workflowConfig(), tmpRoot, 'Task: DeepSeek report fallback', {
      projectCwd: tmpRoot,
      provider: 'opencode',
      model: 'opencode/qwen3-coder-next',
      reportFallbackProvider: {
        provider: 'deepseek-harness',
        model: 'route/report-fallback',
        providerOptions,
      },
      reportDirName: 'deepseek-report-fallback-it',
      structuredCaller,
      onDelegatedAgentUsage: (context) => {
        attemptTelemetry.push({
          provider: context.provider,
          providerModel: context.providerModel,
        });
      },
    });

    const state = await engine.run();

    expect(state.status).toBe('completed');
    expect(readFileSync(join(tmpRoot, '.takt', 'runs', 'deepseek-report-fallback-it', 'reports', 'review.md'), 'utf-8'))
      .toContain('Generated by DeepSeek fallback');
    const fallbackOptions = vi.mocked(runAgent).mock.calls[3]?.[2] as RunAgentOptions;
    expect(fallbackOptions.providerOptions).toEqual(providerOptions);
    expect(fallbackOptions.resolvedProviderOptions).toEqual(providerOptions);
    expect(fallbackOptions.sessionId).toBeUndefined();
    expect(attemptTelemetry).toEqual(expect.arrayContaining([{
      provider: 'deepseek-harness',
      providerModel: 'route/report-fallback',
    }]));
  });

  it('should carry DeepSeek provider options through a report retry with a new session', async () => {
    const providerOptions = {
      deepseekHarness: { maxTokens: 4096, reasoningEffort: 'low' as const },
    };
    queueAttempt(response({
      content: '[IMPLEMENT:1]\nPhase 1 output',
      sessionId: 'deepseek-phase-one-session',
    }));
    queueAttempt(response({ content: '# Report\nfirst attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-1', tool: 'read', input: {} },
    }]);
    queueAttempt(response({ content: '# Report\nretry succeeded' }));
    const structuredCaller: StructuredCaller = {
      judgeStatus: vi.fn().mockImplementation(async (_structured, _tag, _candidates, options) => {
        options.onStructuredPromptResolved?.({
          systemPrompt: 'conductor-system',
          userInstruction: 'structured prompt',
        });
        return { candidateIndex: 0, method: 'structured_output' };
      }),
      evaluateCondition: vi.fn(),
      decomposeTask: vi.fn(),
      requestMoreParts: vi.fn(),
    };
    const engine = new WorkflowEngine(workflowConfig(), tmpRoot, 'Task: report retry', {
      projectCwd: tmpRoot,
      provider: 'deepseek-harness',
      model: 'route/report',
      providerSource: 'runtime-v1',
      providerOptionsProviderSource: 'runtime-v1',
      providerOptions,
      reportDirName: 'report-retry-it',
      structuredCaller,
    });

    const state = await engine.run();

    expect(state.status).toBe('completed');
    expect(runAgent).toHaveBeenCalledTimes(3);
    for (const [, , options] of vi.mocked(runAgent).mock.calls) {
      expect(options?.resolvedProvider).toBe('deepseek-harness');
      expect(options?.resolvedModel).toBe('route/report');
      expect(options?.providerOptions).toEqual(providerOptions);
      expect(options?.resolvedProviderOptions).toEqual(providerOptions);
    }
    expect(vi.mocked(runAgent).mock.calls[0]?.[2]?.sessionId).toBeUndefined();
    expect(vi.mocked(runAgent).mock.calls[1]?.[2]?.sessionId).toBe('deepseek-phase-one-session');
    expect(vi.mocked(runAgent).mock.calls[2]?.[2]?.sessionId).toBeUndefined();
  });
});
